/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vanvu.poly.ui;

import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import vanvu.poly.help.ShareHelper;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import vanvu.poly.DAO.CTHoaDonDAO;
import vanvu.poly.DAO.HoaDonDAO;
import vanvu.poly.DAO.SanPhamDAO;
import vanvu.poly.DAO.VoucherDAO;
import vanvu.poly.model.CTHoaDon;
import vanvu.poly.model.HoaDon;
import vanvu.poly.model.LoaiSP;
import vanvu.poly.model.SanPham;
import vanvu.poly.model.Voucher;

/**
 *
 * @author NGUYEN VAN VU
 */
public class JPanelBanHang extends javax.swing.JPanel {

    /**
     * Creates new form JPanelBanHang
     */
    float sum = 0;
    ArrayList<CTHoaDon> listCTHD = new ArrayList<>();

    public JPanelBanHang() {
        initComponents();

        fillTableSanPham();
        fillCombobox();
        fillTableHDCho();
        fillComboboxVoucher();
        pnlBill.setVisible(false);
        tblHoaDonCho.setRowHeight(30);
        tblSPMua.setRowHeight(30);
        tblSanPham.setRowHeight(30);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxLoai = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHoaDonCho = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        pnlBill = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbMaHD = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbTenKH = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbMaNV = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbNgayTao = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbTrangThai = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lbTienHang = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtTienKhachTra = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        lbTienDu = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbTongtien = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cbxVoucher = new javax.swing.JComboBox<>();
        lbTienVoucher = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSPMua = new javax.swing.JTable();
        btnThemHDCho = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        btnXoaSPMua = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnTaoHD = new javax.swing.JButton();

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        jLabel1.setText("LỌC:");

        cbxLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~~Chọn loại sản phẩm~~" }));
        cbxLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLoaiActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 15))); // NOI18N

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Giá", "Hình", "Ghi chú", "Loại"
            }
        ));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPham);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa đơn chờ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 15))); // NOI18N

        tblHoaDonCho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HD", "Tên KH", "Mã NV", "Ngày tạo", "Trạng thái"
            }
        ));
        tblHoaDonCho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonChoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHoaDonCho);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cbxLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chung", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Mã HD:");

        lbMaHD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Tên KH:");

        lbTenKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbTenKH.setText("Nguyễn Thị Thập");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setText("Mã NV:");

        lbMaNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbMaNV.setText("NV01");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setText("Ngày tạo:");

        lbNgayTao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbNgayTao.setText("19/10/2022");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel11.setText("Trạng thái:");

        lbTrangThai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTrangThai.setForeground(new java.awt.Color(255, 51, 51));
        lbTrangThai.setText("Chờ thanh toán");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(lbMaHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTenKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNgayTao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMaNV)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNgayTao)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTrangThai))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        jLabel13.setText("Tiền hàng:");

        lbTienHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbTienHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTienHang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lbTienHangFocusLost(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        jLabel15.setText("Tiền khách trả:");

        txtTienKhachTra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTienKhachTra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTienKhachTraFocusLost(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        jLabel16.setText("Tiền dư:");

        lbTienDu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Tổng tiền:");

        lbTongtien.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lbTongtien.setForeground(new java.awt.Color(255, 0, 0));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        jLabel18.setText("Voucher:");

        cbxVoucher.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxVoucher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn mã giảm giá" }));
        cbxVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxVoucherActionPerformed(evt);
            }
        });

        lbTienVoucher.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbTienVoucher.setText("0");
        lbTienVoucher.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lbTienVoucherFocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setText("VNĐ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setText("VNĐ");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTienKhachTra)
                    .addComponent(lbTienDu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbTienHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(cbxVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbTienVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTienHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cbxVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTienVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTienKhachTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTienDu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lbTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tblSPMua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên SP", "Giá", "Số lượng", "Tổng tiền"
            }
        ));
        tblSPMua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSPMuaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblSPMua);

        btnThemHDCho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/basket-icon.png"))); // NOI18N
        btnThemHDCho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHDChoActionPerformed(evt);
            }
        });

        btnThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Very-Basic-Calculator-icon.png"))); // NOI18N
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        btnXoaSPMua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete-icon.png"))); // NOI18N
        btnXoaSPMua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSPMuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBillLayout = new javax.swing.GroupLayout(pnlBill);
        pnlBill.setLayout(pnlBillLayout);
        pnlBillLayout.setHorizontalGroup(
            pnlBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
            .addGroup(pnlBillLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlBillLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnXoaSPMua, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(btnThemHDCho)
                .addGap(83, 83, 83)
                .addComponent(btnThanhToan)
                .addGap(114, 289, Short.MAX_VALUE))
        );
        pnlBillLayout.setVerticalGroup(
            pnlBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBillLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBillLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBillLayout.createSequentialGroup()
                                .addComponent(btnXoaSPMua, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBillLayout.createSequentialGroup()
                                .addComponent(btnThemHDCho)
                                .addGap(21, 21, 21))))
                    .addGroup(pnlBillLayout.createSequentialGroup()
                        .addComponent(btnThanhToan)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(pnlBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnTaoHD.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnTaoHD.setText("Tạo hóa đơn");
        btnTaoHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoHDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnTaoHD)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTaoHD)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemHDChoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHDChoActionPerformed
        CTHoaDon cthd = new CTHoaDon();
        CTHoaDonDAO cthdDao = new CTHoaDonDAO();

        for (CTHoaDon ctHD : listCTHD) {
            cthdDao.insert(ctHD);
        }

        fillTableHDCho();
        sum = 0;
        clear();
    }//GEN-LAST:event_btnThemHDChoActionPerformed

    private void btnTaoHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoHDActionPerformed
        String nameKH = JOptionPane.showInputDialog(this, "Nhập tên khách hàng");
        
        if(nameKH == null){
            return;
        }
            HoaDon hd = new HoaDon();
            HoaDonDAO hdDao = new HoaDonDAO();
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            Date date = new Date();
            
            Random generator = new Random();

            int maHD = generator.nextInt(10000);
            String ngayTao = df.format(date);
            

            lbMaHD.setText(String.valueOf(maHD));
            lbTenKH.setText(nameKH);
            lbMaNV.setText(ShareHelper.name);
            lbNgayTao.setText(ngayTao);
            pnlBill.setVisible(true);
            btnXoaSPMua.setVisible(false);
            btnThemHDCho.setVisible(true);
            lbTienVoucher.setVisible(false);
            try {
                setHoaDon(hd, df.parse(ngayTao));
            } catch (ParseException ex) {
                Logger.getLogger(JPanelBanHang.class.getName()).log(Level.SEVERE, null, ex);
            }

            hdDao.insert(hd);
    }//GEN-LAST:event_btnTaoHDActionPerformed

    private void cbxLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLoaiActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblSanPham.getModel();
        SanPhamDAO spDao = new SanPhamDAO();
        ArrayList<SanPham> listSP = new ArrayList<>();

        int loai = 0;
        if (cbxLoai.getSelectedIndex() == 1) {
            loai = 1;
        } else if (cbxLoai.getSelectedIndex() == 2) {
            loai = 2;
        } else if (cbxLoai.getSelectedIndex() == 0) {
            listSP = (ArrayList<SanPham>) spDao.fillAll();
            model.setRowCount(0);

            for (SanPham sp : listSP) {
                model.addRow(new Object[]{sp.getMaSP(), sp.getTenSP(), sp.getGia(), sp.getHinh(), sp.getGhiChu(), sp.getMaLoai() == 1 ? "Đồ ăn vặt" : "Nước giải khác"});

            }
            tblSanPham.setModel(model);
            return;
        }

        listSP = (ArrayList<SanPham>) spDao.findByTenLoai(loai);
        model.setRowCount(0);

        for (SanPham sp : listSP) {
            model.addRow(new Object[]{sp.getMaSP(), sp.getTenSP(), sp.getGia(), sp.getHinh(), sp.getGhiChu(), sp.getMaLoai() == 1 ? "Đồ ăn vặt" : "Nước giải khác"});

        }
        tblSanPham.setModel(model);

    }//GEN-LAST:event_cbxLoaiActionPerformed

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked

        if (!lbMaHD.getText().equals("")) {
            CTHoaDon cthd = new CTHoaDon();
            int row = tblSanPham.getSelectedRow();
            String soLuong = JOptionPane.showInputDialog(this, "Nhập số lượng cần mua");
            if(soLuong == null){
                return;
            }
            DefaultTableModel model = (DefaultTableModel) tblSPMua.getModel();

            String id = (String) tblSanPham.getValueAt(row, 0);

            SanPhamDAO spDao = new SanPhamDAO();
            SanPham sp = spDao.findByID(id);

            setCTHD(cthd, id, soLuong, sp);

            float tongTienHang = Integer.parseInt(soLuong) * sp.getGia();
            sum = sum + tongTienHang;

            lbTienHang.setText(String.valueOf(sum));
            model.addRow(new Object[]{sp.getTenSP(), sp.getGia(), soLuong, tongTienHang});
            tblSPMua.setModel(model);
            
            float tongTien = sum + Float.parseFloat(lbTienVoucher.getText());
            lbTongtien.setText(String.valueOf(tongTien));
        }

    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void txtTienKhachTraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTienKhachTraFocusLost
        if(txtTienKhachTra.getText().equals("")){
            return;
        }

        if (!lbTongtien.getText().equals("")) {
            
            float tienDu = Float.parseFloat(txtTienKhachTra.getText()) - Float.parseFloat(lbTongtien.getText());

            if (tienDu < 0) {
                JOptionPane.showMessageDialog(this, "Số tiền không đủ để thanh toán", "Thông báo", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            lbTienDu.setText(String.valueOf(tienDu));
        }else{
            return;
        }

    }//GEN-LAST:event_txtTienKhachTraFocusLost

    private void tblHoaDonChoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonChoMouseClicked
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        int row = tblHoaDonCho.getSelectedRow();

        int maHD = (int) tblHoaDonCho.getValueAt(row, 0);
        String tenKH = (String) tblHoaDonCho.getValueAt(row, 1);
        String maNV = (String) tblHoaDonCho.getValueAt(row, 2);
        Date ngayTao = (Date) tblHoaDonCho.getValueAt(row, 3);
        String trangThai = (String) tblHoaDonCho.getValueAt(row, 4);

        DefaultTableModel model = (DefaultTableModel) tblSPMua.getModel();

        HoaDonDAO hdDao = new HoaDonDAO();

        List<Object[]> list = hdDao.findByID(maHD);
        model.setRowCount(0);
        for (Object[] obj : list) {
            model.addRow((Object[]) obj);
          
        }
        tblSPMua.setModel(model);

        lbMaHD.setText(String.valueOf(maHD));
        lbTenKH.setText(tenKH);
        lbMaNV.setText(maNV);
        lbNgayTao.setText(String.valueOf(ngayTao));
        lbTrangThai.setText(trangThai);
        lbTienHang.setText(String.valueOf(HoaDonDAO.sumHD));

        HoaDonDAO.sumHD = 0;
        btnThemHDCho.setVisible(false);
        pnlBill.setVisible(true);
        btnXoaSPMua.setVisible(false);
    }//GEN-LAST:event_tblHoaDonChoMouseClicked

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        HoaDonDAO hdDao = new HoaDonDAO();
        CTHoaDonDAO cthdDao = new CTHoaDonDAO();

        if (hdDao.updateTrangThai(Integer.parseInt(lbMaHD.getText()), Float.parseFloat(lbTongtien.getText()))) {
            cthdDao.delete(Integer.parseInt(lbMaHD.getText()));
            for (CTHoaDon cTHoaDon : listCTHD) {
                cthdDao.insert(cTHoaDon);
            }
            JOptionPane.showMessageDialog(this, "Thanh toán thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            fillTableHDCho();
            clear();
        }
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnXoaSPMuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSPMuaActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblSPMua.getModel();
        int row = tblSPMua.getSelectedRow();
        
        CTHoaDon cthd = listCTHD.get(row);
        listCTHD.remove(row);
        CTHoaDonDAO cthdDao = new CTHoaDonDAO();
        HoaDonDAO hdDao = new HoaDonDAO();
        
        cthdDao.deleteSP(cthd.getMaHD(), cthd.getMaSP());
        List<Object[]> list =hdDao.findByID(cthd.getMaHD());
        
        model.setRowCount(0);
        for (Object[] obj : list) {
            model.addRow(obj);
        }
        tblSPMua.setModel(model);
    }//GEN-LAST:event_btnXoaSPMuaActionPerformed

    private void tblSPMuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSPMuaMouseClicked
        btnXoaSPMua.setVisible(true);
    }//GEN-LAST:event_tblSPMuaMouseClicked

    private void lbTienHangFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lbTienHangFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lbTienHangFocusLost

    private void cbxVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxVoucherActionPerformed
        String maVoucher = (String) cbxVoucher.getSelectedItem();
        if(cbxVoucher.getSelectedIndex() == 0){
            lbTienVoucher.setText("0");
            return;
        }
        VoucherDAO vchDao = new VoucherDAO();
        
        Voucher vch = vchDao.findByMaVoucher(maVoucher);
        
        if(Float.parseFloat(lbTienHang.getText()) < vch.getGiaToiThieu()){
            JOptionPane.showMessageDialog(this, "Giá trị đơn hàng của bạn chưa đạt mức tối thiếu khuyến mãi!!");
            return;
        }
        lbTienVoucher.setText("-"+String.valueOf(vch.getTriGia()));
        Float tongTien = Float.parseFloat(lbTienHang.getText()) + Float.parseFloat(lbTienVoucher.getText());
        lbTongtien.setText(String.valueOf(tongTien));
        lbTienVoucher.setVisible(true);
    }//GEN-LAST:event_cbxVoucherActionPerformed

    private void lbTienVoucherFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lbTienVoucherFocusLost

    }//GEN-LAST:event_lbTienVoucherFocusLost

    public void fillTableSanPham() {
        SanPhamDAO spDao = new SanPhamDAO();
        ArrayList<SanPham> listSP = new ArrayList<>();
        DefaultTableModel model = (DefaultTableModel) tblSanPham.getModel();

        listSP.removeAll(listSP);
        listSP = (ArrayList<SanPham>) spDao.fillAll();
        model.setRowCount(0);

        for (SanPham sp : listSP) {
            model.addRow(new Object[]{sp.getMaSP(), sp.getTenSP(), sp.getGia(), sp.getHinh(), sp.getGhiChu(), sp.getMaLoai() == 1 ? "Đồ ăn vặt" : "Nước giải khác"});

        }
        tblSanPham.setModel(model);
    }

    public void fillTableHDCho() {
        HoaDonDAO hdDao = new HoaDonDAO();
        ArrayList<HoaDon> listHD = new ArrayList<>();
        DefaultTableModel model = (DefaultTableModel) tblHoaDonCho.getModel();

        listHD.removeAll(listHD);
        listHD = (ArrayList<HoaDon>) hdDao.fillByTrangThai("Chờ thanh toán");
        model.setRowCount(0);
        double tong = 0;
        for (HoaDon hd : listHD) {
            model.addRow(new Object[]{hd.getMaHD(), hd.getTenKH(), hd.getMaNV(), hd.getNgayTao(), hd.getTrangThai()});

        }
        tblHoaDonCho.setModel(model);
    }

    public void fillCombobox() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbxLoai.getModel();
        SanPhamDAO spDao = new SanPhamDAO();

        List<LoaiSP> listSP = spDao.selectLoaiSP();

        for (LoaiSP loaiSP : listSP) {
            model.addElement(loaiSP.getTenSP());
            cbxLoai.setModel(model);
        }
    }

    public void fillComboboxVoucher(){
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbxVoucher.getModel();
        VoucherDAO vchDao = new VoucherDAO();
        
        List<Voucher> listVCH = vchDao.fillVoucherByDate();
        
        for (Voucher vou : listVCH) {
            model.addElement(vou.getMaVoucher());
            cbxVoucher.setModel(model);
        }
    }
    public void setHoaDon(HoaDon hd, Date date) {
        hd.setMaHD(Integer.parseInt(lbMaHD.getText()));
        hd.setTenKH(lbTenKH.getText());
        hd.setMaNV(ShareHelper.username);
        hd.setNgayTao(date);
        hd.setTrangThai("Chờ thanh toán");
    }

    public void setCTHD(CTHoaDon cthd, String id, String soLuong, SanPham sp) {
        cthd.setMaHD(Integer.parseInt(lbMaHD.getText()));
        cthd.setMaSP(id);
        cthd.setSoLuong(Integer.parseInt(soLuong));
        cthd.setTongTien(sp.getGia() * Integer.parseInt(soLuong));
        cthd.setGhiChu("");

        listCTHD.add(cthd);
    }

    public void clear() {
        DefaultTableModel model = (DefaultTableModel) tblSPMua.getModel();
        pnlBill.setVisible(false);

        model.setRowCount(0);
        lbMaHD.setText("");
        lbTenKH.setText("");
        lbMaNV.setText("");
        lbNgayTao.setText("");
        lbTienHang.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaoHD;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThemHDCho;
    private javax.swing.JButton btnXoaSPMua;
    private javax.swing.JComboBox<String> cbxLoai;
    private javax.swing.JComboBox<String> cbxVoucher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbMaHD;
    private javax.swing.JLabel lbMaNV;
    private javax.swing.JLabel lbNgayTao;
    private javax.swing.JLabel lbTenKH;
    private javax.swing.JLabel lbTienDu;
    private javax.swing.JLabel lbTienHang;
    private javax.swing.JLabel lbTienVoucher;
    private javax.swing.JLabel lbTongtien;
    private javax.swing.JLabel lbTrangThai;
    private javax.swing.JPanel pnlBill;
    private javax.swing.JTable tblHoaDonCho;
    private javax.swing.JTable tblSPMua;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtTienKhachTra;
    // End of variables declaration//GEN-END:variables
}
